name: "Build Custom OpenWrt Installer ISO"

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: '请输入下载地址(扩展名 .img.gz/.img.xz/.img.zip)'
        required: true
        default: 'https://default.example.com/file.img.gz'

jobs:
  build-release:
    name: "Build and Release"
    runs-on: "ubuntu-22.04"
    
    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: "Checking out git repository"
        uses: actions/checkout@v2

      - name: "Install Docker"
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: "Set executable permissions"
        run: |
          chmod +x "${{ github.workspace }}/custom.sh"
          if [ -f "${{ github.workspace }}/supportFiles/custom/build.sh" ]; then
            chmod +x "${{ github.workspace }}/supportFiles/custom/build.sh"
          fi

      - name: "Create output directory"
        run: mkdir -p output

      - name: "Build Docker image"
        run: |
          cd supportFiles/custom
          docker build -t openwrt-builder .

      - name: "Build Image"
        run: |
          download_url="${{ github.event.inputs.download_url }}"
          docker run --rm \
            -v "${{ github.workspace }}:/workspace" \
            -w /workspace \
            openwrt-builder \
            ./custom.sh "$download_url"

      - name: "List build artifacts"
        if: always()
        run: |
          echo "构建产物:"
          find . -type f \( -name "*.iso" -o -name "*.img" \) -ls || true
          echo "output目录内容:"
          ls -la output/ || true

      - name: "Publish to Release"
        if: success() && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: "Custom-Installer-x86_64-ISO"
          body_path: "${{ github.workspace }}/supportFiles/custom/info.md"
          files: |
            output/custom-installer-x86_64.iso
          token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
